# This contains runtime settings for the code.
# Settings specified in the toml should be largely static as these are saved to the repo.

# Note all variables for directories should close the directory as well.
# Like this:     "./data/"
# Not like this: "./data"
# For variables that only contain part of a directory path, only include the closing slash.
# Like this:     "emis/"
# Not like this: "/emis/"


title = "Cancer Primary Care ETL"

[base]
data_dir = "./data/" # Directory for the data files (e.g. "./data/")
db_dsn = "SANDPIT"
db_database = "Data_Lab_NCL_Dev"
db_schema = "GrahamR"

[emis]
data_dir = "emis/"
pipelines = ["CCR", "eSafety", "FIT", "SPR"]

[emis.ccr]
name = "Cancer Care Reviews"
subdir_substrings = ["Cancer"]
db_dest_table = "Monthly_CCR_Safety_Netting_Test"
data_id_cols = ["Start_Date", "Indicator"]
metric_id_prefix = "CAN"
metric_ids = ["004", "005"]
metric_id_map = {"004" = "CAN004 - Cancer Care Review within 12 months", "005" = "CAN005 - Cancer support offered within 3 months"}

[emis.esafety]
name = "e-Safety Netting"
subdir_substrings = ["netting"]
db_dest_table = "Monthly_CCR_Safety_Netting_Test"
data_id_cols = ["Start_Date", "Indicator"]
esafety_indicator_name = "USC referrals safety netted via e-safety netting tool"

[emis.fit]
name = "FIT"
subdir_substrings = ["FIT"]
db_dest_table = "Monthly_FIT_NCL_Test"
data_id_cols = ["Start_Date", "Date_Type"]

[emis.spr]
name = "Social Prescribing Referrals"
subdir_substrings = ["social", "prescrib"]
db_dest_table = "Monthly_Population_Health_Test"
data_id_cols = ["Date_updated", "Indicator_Name"]
indicator_name = "No. of Social Prescribing referrals made within the last 12 months"

[pop]
all_indicators = [276, 91280, 91337, 91355, 91357, 91845, 92588, 94136, 93275, 93553]
area_code_ncl = "nE38000240"
area_codes_london = ["nE38000240", "nE38000244", "nE38000245", "nE38000255", "nE38000256"]
db_dest_table_practice = "Monthly_Population_Health_Test"
db_dest_table_benchmark = "cancer_populationhealth_benchmark_test"
db_dest_table_metadata = "cancer_populationhealth_metadata_test"
query_local_metadata = "./docs/pop_local_metadata.sql"